# start by pulling the '' image
FROM python:3-alpine3.15

WORKDIR /server_flask
# copy the requirements file into the image
COPY server_flask ./

# switch working directory


# install the dependencies and packages